name: Deploy to GitHub Pages
on:
    push:
        branches:
            - master

env:
    CI: true
    FORCE_COLOR: 2
    NODE: 14

jobs:
    deploy:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "${{ env.NODE }}"
                  cache: "npm"
            - run: npm ci
            - name: Build docs
              run: npm run build:docs
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs
                  cname: domutils.js.org
